run:
	uvicorn main:app --host 0.0.0.0 --port 8000 --reload

run-workers:
	uvicorn main:app --host 0.0.0.0 --port 8000 --workers 4 --reload

# run-guni:
# 	gunicorn main:app --workers 4 --worker-class --host 0.0.0.0 --port 8000